name: Code Quality Check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
{% raw %}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
{% endraw %}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox
    - name: Lint with nox
      run: nox -t ci